name: pint

on:
  push:

jobs:
  phpcs:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
      - run: composer install --no-interaction --no-scripts
      - run: vendor/bin/pint --test
